name: Release

on:
  release:
    types: [ created, published ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      repository-projects: write
    strategy:
      matrix:
        goos: [ linux, darwin, windows ]
        goarch: [ amd64, arm64,386 ]
        exclude: # 排除某些平台和架构
          - goarch: arm64
            goos: windows
          - goarch: 386
            goos: darwin

    steps:
      - uses: actions/checkout@v4
      - uses: wangyoucao577/go-release-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          goversion: 1.22
          binary_name: "im-System"
          extra_files: README.md